// <auto-generated />
using System;
using ASU_IS_19_03.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASU_IS_19_03.Migrations
{
    [DbContext(typeof(MsSqlContext))]
    [Migration("20210921092233_Ver1")]
    partial class Ver1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASU_IS_19_03.DB.Model.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("ASU_IS_19_03.DB.Model.Printer", b =>
                {
                    b.Property<int>("PrinterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypePrinterId")
                        .HasColumnType("int");

                    b.HasKey("PrinterId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TypePrinterId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("ASU_IS_19_03.DB.Model.PrinterSklad", b =>
                {
                    b.Property<int>("PrinterSkladId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_of_operation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Operation")
                        .HasColumnType("bit");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int");

                    b.Property<int>("SkladId")
                        .HasColumnType("int");

                    b.HasKey("PrinterSkladId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("SkladId");

                    b.ToTable("PrinterSklads");
                });

            modelBuilder.Entity("ASU_IS_19_03.DB.Model.Sklad", b =>
                {
                    b.Property<int>("SkladId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkladId");

                    b.ToTable("Sklads");
                });

            modelBuilder.Entity("ASU_IS_19_03.DB.Model.TypePrinter", b =>
                {
                    b.Property<int>("TypePrinterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypePrinterId");

                    b.ToTable("TypePrinters");
                });

            modelBuilder.Entity("ASU_IS_19_03.DB.Model.Printer", b =>
                {
                    b.HasOne("ASU_IS_19_03.DB.Model.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASU_IS_19_03.DB.Model.TypePrinter", "TypePrinter")
                        .WithMany()
                        .HasForeignKey("TypePrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("TypePrinter");
                });

            modelBuilder.Entity("ASU_IS_19_03.DB.Model.PrinterSklad", b =>
                {
                    b.HasOne("ASU_IS_19_03.DB.Model.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASU_IS_19_03.DB.Model.Sklad", "Sklad")
                        .WithMany()
                        .HasForeignKey("SkladId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");

                    b.Navigation("Sklad");
                });
#pragma warning restore 612, 618
        }
    }
}
